Refactor
digi-serve/ab_service_process_manager pull request #47
Opened 2023-03-27 06:03 UTC by guyyoo

Refactor ProcessTaskUserExternal

2023-03-27 07:28 UTC, wongpratan approved these changes

2023-03-28 00:08 UTC, Hiro-Nakamura requested changes
OK, it has been a long time since I looked at the `ABProcessTaskUserExternal` and I need to make sure I understand what is supposed to be happening.

From your update, it looks like the `handler/external.js` was simply mimicing the `inbox-update.js` handler, and that isn't correct for this task.

I could be wrong here, so correct me if I am:

The `ABProcessTaskUserExternal` is a process step that notifies a person they need to do something that is outside our system: have a conversation with someone, manually go check something, sign some document, etc... So this task should show a relevant user an Inbox Item that says "Go do something and press the [done] button when finished."

When they press the done button:
- handler/external.js is called, and should:
  - update the process step that it has been completed
  - tell the process to continue to run
  - notify any relevant user of the system that that specific inbox item is done by sending an `inbox.updated` event

- a user's browser should receive the `inbox.updated` message, and then process through the current inbox items in the browser, and update/remove the inbox item.


Now your current updates seem to do the following:

- `handler/external.js` is called and then gathers ALL the roles in the system, and sends them an `inbox.updated` message.

- a user's browser receives the `inbox.updated` message, and then turns around and performs a `put process/inbox/{uuid}` operation.


Since ALL roles are gathered, then EVERY current user of the system will perform the network update.  

I don't think this is what we want.

2023-03-28 00:08 UTC, Hiro-Nakamura commented on handlers/external.js
> -               AB.objectProcessForm().model().update(uuid, {
It would be more efficient to leave the `.update()` here in this service handler.  That we we only perform the update 1 time.

2023-03-28 00:08 UTC, Hiro-Nakamura commented on handlers/external.js
> -                  req.serviceRequest(
Don't forget to tell the original Process to run again.

2023-03-28 06:10 UTC, guyyoo commented
> 

You are correct, I have  already fixed. But for relevant users, Nathan said It's ok to broadcast to all users for now. Thanks!

2023-03-28 16:28 UTC, Hiro-Nakamura approved these changes
These look good.

I like how you did the `errParams` and kept a single `try...catch...` block.

2023-03-29 02:43 UTC, nh758 approved these changes
thanks!

2023-03-29 02:49 UTC, merged